### PR TITLE
Idiomatic go refactor and decouple Crawl from stdout

### PR DESCRIPTION
**Pull request by hoenn**
:wave: 
I saw "Cleaner code" as a bullet in upcoming features and figured I'd give it a shot. There are a lot of changes are mostly style changes to better fit the Go style guide and idiomatic go

I did endeavor to decouple the `crawl` func from printing to `stdout` but instead to a writer interface to better work with more use cases (such as fronting this app with an http server).

Changes:
- Improved goreportcard results [my fork](https://goreportcard.com/report/github.com/hoenn/hakrawler) -> Go Report Card
- Removed `.` imports [Import Dot](https://github.com/golang/go/wiki/CodeReviewComments#imports)
- Refactored indentation (favor early returns) [Indent Error Flow](https://github.com/golang/go/wiki/CodeReviewComments#indent-error-flow)
- Added comments to exported names [Doc Comments](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments)
- Created `collector` pkg and `Collector` struct to contain more of the config
- Decoupled (what is now) `Collector.Crawl` from stdout, instead pass in an `io.Writer`. `main.go` passes in `bufio.NewWriter(os.Stdout)`
- `Collector.Crawl` returns an `[]*http.Requests` and leaves the "print requests to file" functionality up to the caller.
- Refactor anonymous `colly.OnHTML` funcs to be named closures (and simplify the main code path `c.Crawl`).
- Handle an error in waybackurls.go that allowed a nil pointer exception [Handle Errors](https://github.com/golang/go/wiki/CodeReviewComments#handle-errors)
- `chmod -x` on a few files :smile: 

I normally wouldn't submit a PR so big, but I got carried away. If you're interested in merging please pull down this branch and build it, I'm not exactly sure how you were using `stdin` to pipe input but I'd like to make sure that remained functionally identical for your use-case.

### CODE REVIEW

**Comment by hakluke** [comment]
Hey @hoenn!
I absolutely love these changes! Unfortunately there's now some conflicts and I'm finding it difficult to figure out how to resolve some of them, is there any chance you would be willing to take a look? I think the problem is that I merged in another PR that was submitted not long before this one, and some of the changes that were made there conflicted with these ones.

**Comment by hoenn** [comment]
Conflicts should be resolved.

**Comment by hakluke** [comment]
Hey @hoenn!
I've noticed that since I've merged this I have had an issue where hakrawler hangs indefinitely. For example, try `echo "youtube.com" | hakrawler`.

I have a feeling it might be a waitgroup that never finishes.

**Comment by hakluke** [comment]
Nevermind fixed it! It was just an unclosed channel :)

**Pull request merged**
