### PR TITLE
Feat: Add Flag to Disable Following HTTP Redirects

### PR DESCRIPTION
**Pull request by ErikOwen**

### CODE REVIEW

**Review by austintraver — CHANGES_REQUESTED** [review]
Hopefully @hakluke will have a chance to take a look at this, this would be very useful. I reviewed it and it looks good, though I made a couple of syntax changes, which you can optionally choose to include in your contribution. Anyhow: thanks for writing this up!

**Comment by ErikOwen** [comment]
Thanks for the suggestions, @austintraver!

**Review by austintraver — APPROVED** [review]

**Comment by austintraver** [comment]
LGTM @ErikOwen

**Comment by ErikOwen** [comment]
@hakluke - would you mind taking a look at this PR when you get the chance?

**Review by hakluke — APPROVED** [review]
looks good, and a handy feature!

**Comment by hakluke** [comment]
Merged - thanks @ErikOwen and @austintraver. Apologies for the delay.

**Comment by ErikOwen** [comment]
Thank you 🙏

**Pull request merged**
