### PR TITLE
added support for simple search/match string

### PR DESCRIPTION
**Pull request by dogasantos**
Hi,

I had a need to look for specific strings on resources (links, images, css resources, and so on), so I decided to modify your code to accomplish this purpose. 

Here is a sample output:

```
$ echo https://www.o2.co.uk/ | ./hakrawler -m extras-promo-xxl-short-1100-210621.jpg
[https://www.o2.co.uk/extras/disney-plus]->[img] https://www.o2.co.uk/documents/456036/2514736/extras-promo-xxl-short-1100-210621.jpg/913e6f94-6bec-7ee1-d904-a2b730062c3c?t=1625587100825
$ 
``` 

We have the page where the match occurs, the tag (img) and the full link that matches the string.

For some limitation on gocolly (seems to), some urls won't match. Not sure why, but in general it works just fine.

The next step would be a full body search while crawling, and a regex match.

As you don't have a devel branch, this is a request to merge with your master, but feel free to reject or accept.

Thanks

### CODE REVIEW

**Comment by dogasantos** [comment]
not mature enough.

**Comment by dogasantos** [comment]
there it go

**Comment by dogasantos** [comment]
dead project.

**Comment by hakluke** [comment]
Hey! Sorry I didn't get to this. I think in this case it would be better to just use grep anyway. Thanks for the PR though!

**Comment by dogasantos** [comment]
any?

**Comment by hakluke** [comment]
Sorry I just don't think it's necessary for this tool, and hakrawler would already print out the URLs in the example you mentioned anyway.

Providing a custom search/match string for a specific use-case is not something that I think will be widely useful, so I'd rather keep the main branch simple.

Thanks again for the PR though!

**Pull request closed without merging**
